### ISSUE TITLE
Modificar las coordenadas

### ISSUE THREAD

**Issue by DantDP** [DantDP/IWVG.SwC.DantDP#1]
Modificar las coordenadas
[Más info](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-las-coordenadas)
@AlbertoNitro aquí están las [pautas](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo) de trabajo

**Comment by AlbertoNitro** [comment]
Funcionalidad ya implementada. Cierro ticket
