### ISSUE TITLE
Poner en mayúsculas

### ISSUE THREAD

**Issue by DantDP** [DantDP/IWVG.SwC.DantDP#2]
Poner en mayúsculas
[Más info](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-poner-en-may%C3%BAsculas)
@Chinegua [aquí ](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo)están las pautas de trabajo

**Comment by Chinegua** [comment]
Done

**Comment by DantDP** [comment]
No me aparece la rama correspondiente al issue. Revisa porque solo me aparece develop.

**Comment by Chinegua** [comment]
Done @DantDP

**Comment by DantDP** [comment]
Vale. Solucionado eso.
