### ISSUE TITLE
Menor denominador

### ISSUE THREAD

**Issue by DantDP** [DantDP/IWVG.SwC.DantDP#3]
Método para menor denominador
[Más info
](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-menor-denominador) @Chinegua [aquí ](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo)están las pautas de trabajo

**Comment by Chinegua** [comment]
Done

**Comment by DantDP** [comment]
@Chinegua el método está mal. Da true si el denominador es **mayor**, cuando debe ser al revés. 
Además, en el test debe probarse tanto el caso de que dé true como false, pero solo aparece el de true.

**Comment by DantDP** [comment]
@Chinegua antes ampliaste bien el test, pero en base a un método mal hecho, por lo que al corregir dicho método, el test correspondiente falla.
Además, al subir tu develop, falta el archivo del **proyecto**.

**Comment by DantDP** [comment]
Ya está fijado el fallo. Cierro
