### ISSUE TITLE
Menor decimal

### ISSUE THREAD

**Issue by DantDP** [DantDP/IWVG.SwC.DantDP#4]
Menor decimal
[Más info](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-menor-decimal)
@Chinegua [aquí ](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo)están las pautas de trabajo

**Comment by Chinegua** [comment]
Done @DantDP
