### ISSUE TITLE
Hallar la media

### ISSUE THREAD

**Issue by DantDP** [DantDP/IWVG.SwC.DantDP#5]
Hallar la media
[Más info](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-conocer-la-media)
@AlbertoNitro [aquí ](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo)están las pautas de trabajo

**Comment by AlbertoNitro** [comment]
Ticket cerrado. Funcionalidad implementada.
