### ISSUE TITLE
Total de decimales

### ISSUE THREAD

**Issue by DantDP** [DantDP/IWVG.SwC.DantDP#6]
Hallar tamaño
[Más info](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-para-conocer-el-tama%C3%B1o)
@AlbertoNitro [aquí ](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo)están las pautas de trabajo

**Comment by AlbertoNitro** [comment]
Funcionalidad ya implementada. Tciket cerrado.

No obstante, el metodo que me has pedido (calcualr cuantos numeros existen dentro de una coleccion de decimales) ya esta implementado en la clase.

**Comment by DantDP** [comment]
Tienes razón. Para prevenir redundancias borro esta rama y te asigno una nueva tarea.

**Comment by DantDP** [comment]
Método más de tres
Más [info](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/Documentaci%C3%B3n#m%C3%A9todo-m%C3%A1s-de-tres)
@AlbertoNitro [aquí ](https://github.com/DantDP/IWVG.SwC.DantDP/wiki/M%C3%A9todo-de-trabajo) están las pautas de trabajo
